/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRiskScoreRouteImport } from './routes/api/risk-score'
import { Route as ApiReverseImageSearchRouteImport } from './routes/api/reverse-image-search'
import { Route as ApiDraftTakedownRouteImport } from './routes/api/draft-takedown'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRiskScoreRoute = ApiRiskScoreRouteImport.update({
  id: '/api/risk-score',
  path: '/api/risk-score',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReverseImageSearchRoute = ApiReverseImageSearchRouteImport.update({
  id: '/api/reverse-image-search',
  path: '/api/reverse-image-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftTakedownRoute = ApiDraftTakedownRouteImport.update({
  id: '/api/draft-takedown',
  path: '/api/draft-takedown',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/api/draft-takedown': typeof ApiDraftTakedownRoute
  '/api/reverse-image-search': typeof ApiReverseImageSearchRoute
  '/api/risk-score': typeof ApiRiskScoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/api/draft-takedown': typeof ApiDraftTakedownRoute
  '/api/reverse-image-search': typeof ApiReverseImageSearchRoute
  '/api/risk-score': typeof ApiRiskScoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/api/draft-takedown': typeof ApiDraftTakedownRoute
  '/api/reverse-image-search': typeof ApiReverseImageSearchRoute
  '/api/risk-score': typeof ApiRiskScoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/draft-takedown'
    | '/api/reverse-image-search'
    | '/api/risk-score'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/draft-takedown'
    | '/api/reverse-image-search'
    | '/api/risk-score'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/draft-takedown'
    | '/api/reverse-image-search'
    | '/api/risk-score'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ApiDraftTakedownRoute: typeof ApiDraftTakedownRoute
  ApiReverseImageSearchRoute: typeof ApiReverseImageSearchRoute
  ApiRiskScoreRoute: typeof ApiRiskScoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/risk-score': {
      id: '/api/risk-score'
      path: '/api/risk-score'
      fullPath: '/api/risk-score'
      preLoaderRoute: typeof ApiRiskScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reverse-image-search': {
      id: '/api/reverse-image-search'
      path: '/api/reverse-image-search'
      fullPath: '/api/reverse-image-search'
      preLoaderRoute: typeof ApiReverseImageSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draft-takedown': {
      id: '/api/draft-takedown'
      path: '/api/draft-takedown'
      fullPath: '/api/draft-takedown'
      preLoaderRoute: typeof ApiDraftTakedownRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ApiDraftTakedownRoute: ApiDraftTakedownRoute,
  ApiReverseImageSearchRoute: ApiReverseImageSearchRoute,
  ApiRiskScoreRoute: ApiRiskScoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
